name: "Repo A CI"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Event name
        required: true
      data:
        description: Event data
        required: true
      type:
        description: Event type
        required: true
        default: create

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger Repo B
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: varunner/repo-b
        event-type: ${{ github.event.inputs.type }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
