name: "Repo A CI"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Event name
        required: true
      data:
        description: Event data
        required: true
      type:
        description: Event type
        required: true
        default: create
  pull_request:

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
    - name: test
      shell: bash
      run: | 
        if [[ ! "$GITHUB_REF"  = "refs/tags/"* ]]; then
          if [[ "$GITHUB_EVENT_NAME" = "pull_request" ]]; then
            HEAD_REF=$(printf "%q" "$GITHUB_HEAD_REF")
            HEAD_REF=${HEAD_REF/refs\/heads\//}
            echo "$HEAD_REF"  
          else 
            REF=$(printf "%q" "$GITHUB_REF")
            REF_BRANCH=${REF/refs\/pull\//}
            REF_BRANCH=${REF_BRANCH/refs\/heads\//}
            echo "$REF_BRANCH"
          fi
        else 
          REF=$(printf "%q" "$GITHUB_REF")
          REF_BRANCH=${REF/refs\/tags\//}
          echo "$REF_BRANCH"
        fi
            
     - name: Trigger Repo B
       uses: peter-evans/repository-dispatch@v1
       with:
         token: ${{ secrets.GH_PAT }}
         repository: varunner/repo-b
         event-type: ${{ github.event.inputs.type }}
         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
