name: "Repo A CI"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Event name
        required: true
      data:
        description: Event data
        required: true

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger Repo B
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: varunner/repo-b
        event-type: trigger
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
