name: "Repo A CI"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Event name
        required: true
      data:
        description: Event data
        required: true
      type:
        description: Event type
        required: true
        default: create
  pull_request:

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
    - name: test
      run: | 
			  if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "${{ steps.branch.outputs.head_ref_branch }}"
          else
            echo "${{ steps.branch.outputs.ref_branch }}"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "$(eval printf "%s" "$REF_BRANCH")"
        fi
            
    # - name: Trigger Repo B
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.GH_PAT }}
    #     repository: varunner/repo-b
    #     event-type: ${{ github.event.inputs.type }}
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
