name: "Repo A CI"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Event name
        required: true
      data:
        description: Event data
        required: true
      type:
        description: Event type
        required: true
        default: create
  pull_request:
    types: [opened, reopened, closed]

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:

    - name: Extract PR
      run: |
        PR_NUMBER=$(echo "${{ github.ref }}"| awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "PR NUMBER: ${{github.event.issue.number}}"
        echo "PR NUMBER: ${{github.event.number}}"
        echo "::set-output name=value::${{ github.event.number }}"

    - name: Trigger Repo B
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: varunner/repo-b
        event-type: ${{ github.event.inputs.type || 'test'}}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
